### ISSUE TITLE
Syntax highlighting for tutorials

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#209]
Perhaps geshi? http://geshi.org/

What we have now (below) isn't very good:

![screen shot 2015-09-26 at 1 55 20 pm](https://cloud.githubusercontent.com/assets/737638/10116065/42c0948a-6456-11e5-8464-f04f92490f6a.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/212
I forgot to put the css and js file for the highlighting before, now it should works.

**Comment by dhowe** [comment]
We need to support JS, Java, YAML, and JSON.
Doesn't seem to be fully working:

![screen shot 2015-09-29 at 11 17 01 am](https://cloud.githubusercontent.com/assets/737638/10154701/51411a36-669d-11e5-9ddf-befe089a81ba.png)

**Comment by cqx931** [comment]
Because in stand YML format, the first line should always start with 
"--- ", if an empty line or "--- " is added, it works fine.
http://www.rednoise.org/rita/tutorial/grammars.php
<img width="364" alt="2015-10-09 4 26 10 pm" src="https://cloud.githubusercontent.com/assets/3056154/10389236/7bd1ad8a-6ea2-11e5-944f-cdc337bfabad.png">
<img width="210" alt="2015-10-09 4 26 03 pm" src="https://cloud.githubusercontent.com/assets/3056154/10389246/7e529394-6ea2-11e5-8251-4751a0c92cf6.png">

**Comment by dhowe** [comment]
good
