### ISSUE TITLE
Change JS KWICModel examples (2) to work like Java (with buttons)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#237]
DOM and p5js

**Comment by CyrusSUEN** [comment]
Please verify: https://github.com/dhowe/RiTaJS/pull/7

**Comment by dhowe** [comment]
Please check spacing
![screen shot 2015-11-05 at 12 30 13 pm](https://cloud.githubusercontent.com/assets/737638/10959882/fa098166-83b8-11e5-9b99-2cf207372bab.png)

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/RiTaJS/pull/8

**Comment by dhowe** [comment]
What is the status of this PR? Is it still needed?

**Comment by CyrusSUEN** [comment]
> Is it still needed?

Yes. The spacing issue was fixed https://github.com/CyrusSUEN/RiTaJS/commit/951d171937f5cada484fbe1b11c114d807ee1882 but the PR wasn't accepted.
Recreate a PR for this: https://github.com/dhowe/RiTaJS/pull/11

Also created another PR including this fix and another fix for an issue which reintroduced the old UI in KWIC dom example:
![capture](https://cloud.githubusercontent.com/assets/2461812/11614067/9c6e65d6-9c71-11e5-81f6-a14bc10d84f7.PNG)
https://github.com/dhowe/RiTaJS/pull/12
Because I'm not sure whether the change was intentional.

**Comment by CyrusSUEN** [comment]
Done and closing
