### ISSUE TITLE
Fix tests after corrected phonemes are added in rita_newdict.js

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#257]

**Comment by CyrusSUEN** [comment]
Fixed 4 of 6 test cases:
testIsRhymeStringString
testIsAlliterationStringString
testIsRhymeStringStringBoolean
testRhymesString

The remaining 2 not fixed. Not sure how to improve the tests for them
TODO:  better tests 
testAlliterationsString
testAlliterationsStringInt

PR: https://github.com/dhowe/RiTa/pull/258

**Comment by CyrusSUEN** [comment]
RiTaJS passed: https://github.com/dhowe/RiTa/issues/265#issuecomment-168538980

RiTa still failed because of the twisted meaning of 'REMOTE_TESTING'.
If its value is set to true, should it mean to do the remote test or skip the test?

If it meant to do it, then merge with PR https://github.com/dhowe/RiTa/pull/273 which passes the CI test.

**Comment by CyrusSUEN** [comment]
New ticket: https://github.com/dhowe/RiTa/issues/285
Closing this one
