### ISSUE TITLE
Problem with words starting with vowel phones in alliterations()

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#293]
See RiTa: rita.test.KnownIssuesTest.java::testAlliterations

**Comment by cqx931** [comment]
This was the first fix to this ticket
https://github.com/dhowe/RiTa/commit/b3881b59a0621cb4f5c139b4f10c2049a5aaea04

But new issues emerged during the testing
Currently, the alliteration function always check the firstStressedSyllable, so it will regard "withdraw" as an alliteration for "dog" (draw - dog)

https://github.com/dhowe/RiTa/pull/378

So instead of the the firstStressedSyllable, the first phoneme should be check in oder to get this fixed.

**Comment by dhowe** [comment]
so we are not counting assonance, in this algorithm, is that correct?
```
    ok(!lex.isAlliteration("octopus", "oblong"));
    ok(!lex.isAlliteration("omen", "open"));
    ok(!lex.isAlliteration("amicable", "atmosphere"));
```

**Comment by cqx931** [comment]
Yes, I think so.  And we will return null if the user try to get assonance with words starting in vowels, correct?
