### ISSUE TITLE
Fork for french phonems

### ISSUE THREAD

**Issue by fredericpierron** [dhowe/RiTa#345]
Hi
Is there a fork somewhere for french phonems? If not, what would be the best way to start it?

F

**Comment by dhowe** [comment]
It would be possible, but not easy. There are various types of rules specific to English throughout the code: for conjugation, pluralization, pos-tagging, stemming, etc. Depending on what you wanted to do, each of these would have to be replaced by a corresponding French rule. 

Perhaps the first step would be factoring out all the language-specific code into a single place (which would probably be easier to do in the JavaScript code, rather than the Java)

**Comment by fredericpierron** [comment]
Sorry, but where's the JS code, I am going through the numerous folders without seing it. I have found the RiTa-1.1.40.zip : is-it the starting point for the JS sources ?

**Comment by fredericpierron** [comment]
Ho, it is another repository ;-) Sorry.

**Comment by fredericpierron** [comment]
Yes. There's a lot of work. 
Maybe create a reference file for language, such as fr_FR, us_US,...
You are using the ArpaBet for phonems, which is english oriented table. Do you think other tables would work ? 
Also, there's the english data to replace, but also many rules to add for every languages.
I'm not sure to be able to do that. I will look at some python ready-solutions before ;-).
Great work.
F

**Comment by dhowe** [comment]
thanks, good luck to you!
