### ISSUE TITLE
Check singularize/pluralize/getPosTags problems in KnownIssues-tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#369]

**Comment by cqx931** [comment]
singularize and pluralize problems are done.

Though not sure about these in getPosTags problems

      deepEqual(RiTa.getPosTags("biped"), [ "nn" ]); // transform 3
      deepEqual(RiTa.getPosTags("by illegal means"),  ["in", "jj", "nn"]); //transform 7 -> 11

      var resultArr = RiTa.getPosTags("Dave dances");// transform 10
      var answerArr = [ "nnp", "vbz" ];
      deepEqual(answerArr, resultArr);

1."biped" for this one, the simplest solution I can come up with is to add "biped" into the dictionary and mark it as 'nn', since this is very rare case for words end with 'ed'

2.Though in dictionary, 'means' is marked as 'nn', it get first transformd by rule 7(nn -> nns) then in rule 11(nns -> vbz)
For what case is rule 7 intended for? At least when I comment it out, it doesn't break any test...

3.not sure about "Dave dances"...
With the current rule 10, it won't transform the tag from 'nn' to 'nnp', when it is capital and at sentence start. 'Dove flies.' and 'Dave dances.' is hard to be distinguished from...
I can try to check whether the singularized form of the word can be found in the dictionary or not... but this shall be relatively low priority...

**Comment by dhowe** [comment]
> 1."biped" for this one, the simplest solution I can come up with is to add "biped" into the dictionary and mark it as 'nn', since this is very rare case for words end with 'ed'

Yes, Ok. I was trying to think of a counter-example for that pos-tagging rule and that was the only one I could come up with.

> 2.Though in dictionary, 'means' is marked as 'nn', it get first transformd by rule 7(nn -> nns) then in rule 11(nns -> vbz)
> For what case is rule 7 intended for? At least when I comment it out, it doesn't break any test...

I think that the only time this rule can validly fire is in combination with 1a, so perhaps we can mkae it a condition inside 1a?

> 
> 3.not sure about "Dave dances"...
> With the current rule 10, it won't transform the tag from 'nn' to 'nnp', when it is capital and at sentence start. 'Dove flies.' and 'Dave dances.' is hard to be distinguished from...
> I can try to check whether the singularized form of the word can be found in the dictionary or not... but this shall be relatively low priority...

Yes, good. 'Dove flies' is actually not correct -- it would be '[The|A|That|This] dove flies]', so I think we can try that.: if i == 0 and the word is not in the dictionary, then make it nnp.

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/commit/7d245ba7d3397e5508e8243a08a6cf5c1ce002b0

The issues mentioned above are all solved.
One test case is still left in KnownIssues, and it is fixed here, please check:
https://github.com/dhowe/RiTaJS/pull/54
https://github.com/dhowe/RiTa/pull/407
