### ISSUE TITLE
RiLexicon: random plural nouns return empty array

### ISSUE THREAD

**Issue by Conn0** [dhowe/RiTa#408]
As you can see in this sketch on openprocessing: https://www.openprocessing.org/sketch/419796 Rita should be generating a plural noun between their and lifting in the second line, but it comes up blank. The line of code I'm using that is not working:

lexicon.randomWord("nns")

ccing @indefinit to follow this issue

**Comment by cqx931** [comment]
I don't see any link of the sketch you mentioned, could you please update the link?

**Comment by Conn0** [comment]
Sorry about that, edited it in.

**Comment by cqx931** [comment]
Thanks for reporting the issue!
In the latest version,we have removed all the "nns" from rita dictionary to reduce the total size of it. That's why you got nothing back from lexicon.randomWord("nns").
I will add a warning messages on this issue to make it less confusing.

To achieve the same result, you can use  `RiTa.pluralize(lexicon.randomWord("nn"))`
