### ISSUE TITLE
RiTa.singularize("Money") is undefined

### ISSUE THREAD

**Issue by koltclassic** [dhowe/RiTa#493]
This also happens for RiTa.singularize("Beef")

**Comment by dhowe** [comment]
Are you using Java, or JS. And which version of RiTa?
thanks

**Comment by koltclassic** [comment]
Sorry about that; using latest JS (1.3.11)

**Comment by koltclassic** [comment]
looks like the error is being throw in the `_applyContext` function (line 3915 of rita-full)
```
      // transform 10(dch): convert common nouns to proper
      // nouns when they start w' a capital
      if (sW(tag, "nn") && (word.charAt(0)===word.charAt(0).toUpperCase())) {
        //if it is not at the start of a sentence or it is the only word
        // or when it is at the start of a sentence but can't be found in the dictionary
        if(i != 0 || words.length===1 || (i == 0 && !this._lexHas('nn', RiTa.singularize(word).toLowerCase()))){
           tag = eW(tag, "s") ? "nnps" : "nnp";
           this._ct(10, word, tag);
        }
      }
```

**Comment by cqx931** [comment]
Thanks @koltclassic! Found the bug and it is fixed here: https://github.com/dhowe/RiTaJS/pull/94/commits/e5b7c468b8a271544a64991b0b8a76ec27f75cdc

**Comment by koltclassic** [comment]
@cqx931 Awesome! Just out of curiosity, could you briefly explain what was going on here? Trying to follow along with what is going on in the background can get a bit confusing sometimes 😅 Thank you!

**Comment by cqx931** [comment]
Hi @koltclassic 

Here is how [singularize()](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L190) works in RiTaJS:

1.Check wether the word is in [SINGULAR_RULES ](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L5392). 
If yes, return the corresponding singular form.

2.If not, return the word stem using [Pling stemmer](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L4907) 
This is where things are going wrong for 'Money' and 'Beef'.

In pling stemmer, the first task is checking whether the word is in [categoryIRR],
which is used to map some irregular plural nouns. (https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L4858). 

Both "money" and "beef" are on this word list, but they are on the singular side in the word pair([monies, money] and [beefs, beef]). Because the stemmer only maps plural to singular, it can't find the corresponding singular form a singular word on this list. Then it returns this 'undefined' result without going through the rest of the rules (which it should, and this is the fix).

I hope this makes sense to you and please let me know if you have further questions!

**Comment by cqx931** [comment]
close
